sudo: required

language: python

python:
  - "3.5"

services:
  - docker
  - mongodb

env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  MONGODB_URL: 127.0.0.1

before_install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - py.test --cov echo --cov-report term-missing

after_success:
  - coveralls
