sudo: required

language: python

python:
  - "3.5"

services:
  - docker
  - mongodb

env:
  COMMIT_AUTHOR_EMAIL: "one.echo.story.bot@gmail.com"
  DOCKER_COMPOSE_VERSION: 1.8.0
  ENCRYPTION_LABEL: "2e146433b7bc"
  MONGODB_URI: 127.0.0.1
  MONGODB_DB_NAME: test

before_install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - py.test --cov echo --cov-report term-missing

after_success:
  - coveralls
  - ./scripts/deploy-static.sh
