version: '2'
services:
  mongo:
    image: mongo
  bot:
    build: .
    command: ./scripts/start.sh
    environment:
      - PORT=8080
      - GA_ID="UA-86885596-3"
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
